theme: jekyll-theme-cayman
title: ProjectHydra

exclude:
  - components/
  - build/
  - main/
  - data/
  - payloads/
  - firmware_release/
  - Doxyfile
  - CMakeLists.txt
  - partitions.csv
  - sdkconfig
  - sdkconfig.defaults
  - dependencies.lock
